# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0009_auto_20170928_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='forum_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Subscribers'),
        ),
    ]
