# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-01 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_conversation', '0011_topic_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notifications_sent',
            field=models.BooleanField(default=False, verbose_name='Notifications sent'),
        ),
    ]
